IranTimes/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace NewShop
{
    public class Comment
    {
        [Key]
        public int CommentID { get; set; }
        public int PageID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string Text { get; set; }
        public int? ParentID { get; set; }
        public DateTime CreateDate { get; set; }
        public  Page Page { get; set; }
        public Comment Parent { get; set; }
        public List<Comment> Child { get; set; }
    }
}

IranTimes/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using NewShop;
using System;

namespace IranTimes
{
    public class NewsController : Controller
    {
        private IPageRepository _pageRepository;
        private ICommentRepository _commentrepository;
        public NewsController(IPageRepository pageRepository,ICommentRepository commentRepository)
        {
            _pageRepository = pageRepository;
            _commentrepository = commentRepository;
        }
        public IActionResult ShowNews(int id)
        {
            var model = _pageRepository.GetPageById(id);
            model.Visit += 1;
            _pageRepository.Save();
            return View(model);
        }
        public IActionResult ShowGroups()
        {
            return View();
        }
        public IActionResult Comment(int id, string name, string text, string website, string email)
        {
            
                Comment newcomment = new Comment()
                {
                    Email = email,
                    Name = name,
                    Text = text,
                    WebSite = website,
                    PageID = id,
                    CreateDate = DateTime.Now
                }; 
                _commentrepository.AddComment(newcomment);
                _commentrepository.Save();
            return Json(newcomment);       
        }
     
    }
}

IranTimes/Controllers/RoleManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace IranTimes.Controllers
{
    [Authorize(Roles = "Owner")]
    public class RoleManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _rolemanager;
        public RoleManagerController(RoleManager<IdentityRole> roleManager)
        {
            _rolemanager = roleManager;
        }
        public IActionResult Index()
        {
            var roles = _rolemanager.Roles.ToList();
            return View(roles);
        }
        public IActionResult AddRoles()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRoles(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model == null) return NotFound();
                var role = new IdentityRole(model.RoleName);
                var result = await _rolemanager.CreateAsync(role);
                if (result.Succeeded) return RedirectToAction("Index");
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRole(string Id)
        {
            if (string.IsNullOrEmpty(Id)) return NotFound();
            var role = await _rolemanager.FindByIdAsync(Id);
            if (role == null) return NotFound();
            await _rolemanager.DeleteAsync(role);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditeRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var role = await _rolemanager.FindByIdAsync(id);
            if (role == null) return NotFound();
            RoleViewModel model = new RoleViewModel()
            {
                  id=role.Id,
                  RoleName=role.Name
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditeRole(RoleViewModel model)
        {
            if (model == null) return NotFound();
            var role = await _rolemanager.FindByIdAsync(model.id);
            if (role == null) return NotFound();
            role.Name = model.RoleName;
            var result = await _rolemanager.UpdateAsync(role);
            if (result.Succeeded) return RedirectToAction("Index");
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View();
        }
    }
}

IranTimes/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using NewShop;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IranTimes
{
    public class SearchController : Controller
    {
        private readonly IPageRepository _pageRepository;
        public SearchController(IPageRepository pageRepository)
        {
            _pageRepository = pageRepository;
        }
        public IActionResult Index(string q)
        {
            ViewBag.name = q;
           var model= _pageRepository.Search(q);
            return View(model);
        }
    }
}

IranTimes/Controllers/UserManagerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using IranTimes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace IranTimes.Controllers
{
    [Authorize(Roles = "Owner")]
    public class UserManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public UserManagerController
            (RoleManager<IdentityRole> roleManager,
            UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {

            var model = _userManager.Users.Select(s => new IndexViewModel()
            {
                Id = s.Id,
                UserName = s.UserName,
                Email = s.Email,

            }).ToList();

            foreach (var item in model)
            {
                var user = await _userManager.FindByEmailAsync(item.Email);
                var role = await _userManager.GetRolesAsync(user);

                item.RoleName = role;
            }


            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> EditeUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            IdentityUserViewModel model = new IdentityUserViewModel()
            {
                Id = user.Id,
                Name = user.UserName
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditeUser(IdentityUserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.Id);
            if (user == null) return NotFound();
            user.UserName = model.Name;

            var result = await _userManager.UpdateAsync(user);
            if (result.Succeeded) return RedirectToAction("Index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddUserToRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var rols = _roleManager.Roles.ToList();
            var userrole = await _userManager.GetRolesAsync(user);
            var valid = rols.Where(w => !userrole.Contains(w.Name)).ToList();

            var model = new AddUserToRoleViewModel()
            {
                Id = id
            };
            foreach (var role in valid)
            {
                model.UserRoleNames.Add(new UserRoleName()
                {
                    RoleName = role.Name
                });
            }


            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToRole(AddUserToRoleViewModel model)
        {

            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.Id);
            if (user == null) return NotFound();
            var rolerequest = model.UserRoleNames
                .Where(w => w.IsSelected)
                .Select(s => s.RoleName)
                .ToList();

            var result = await _userManager.AddToRolesAsync(user, rolerequest);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> RemoveUserFromRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var userrole = await _userManager.GetRolesAsync(user);
            var model = new AddUserToRoleViewModel()
            {
                Id = id
            };
            foreach (var role in userrole)
            {
                model.UserRoleNames.Add(new UserRoleName()
                {
                    RoleName = role
                });
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveUserFromRole(AddUserToRoleViewModel model)
        {
            if (model == null) return NotFound();
            var user = await _userManager.FindByIdAsync(model.Id);
            if (user == null) return NotFound();
            var roles = _roleManager.Roles.ToList();

            var requestrole = model.UserRoleNames
                .Where(w => w.IsSelected)
                .Select(s => s.RoleName)
                .ToList();
            var result = await _userManager.RemoveFromRolesAsync(user, requestrole);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            await _userManager.DeleteAsync(user);
            return RedirectToAction("Index");
        }


    }
}

IranTimes/Views/Shared/_BoxView.cshtml
@model Page
    
            <div class="tc-ch wow fadeInDown animated" data-wow-duration=".8s" data-wow-delay=".2s" style="visibility: visible; animation-duration: 0.8s; animation-delay: 0.2s; animation-name: fadeInDown;">

                <div class="tch-img">
                    <a asp-controller="News" asp-action="ShowNews" asp-route-id="@Model.id"><img src="~/ImageFile/@Model.ImageName" class="img-responsive" alt=""></a>
                </div>

                <h3>
                    <a href="singlepage.html">

                       @Model.Title
                    </a>
                </h3>
                <h6>
                    گروه<a href="singlepage.html">

                        @Model.PageGroup.GroupName
                    </a>
                </h6>
                <p>@Model.ShortDescription  </p>
               
                <h5>
                    @Model.CreateDate.ToShamsi()
                </h5>
                <div class="bht1">
                    <a asp-controller="News" asp-action="ShowNews" asp-route-id="@Model.id">
                        ادامه مطلب
                    </a>
                </div>
               
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
           
    

IranTimes/Views/Shared/_Comment.cshtml
@model Page

<div class="coment-form" id="com">
    <h4>نظرات</h4>
    <form action="#" method="post">
        <input id="txtname" type="text" value="نام" name="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
        <input id="txtemail" type="email" value="ایمیل" name="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
        <input id="txtweb" type="text" value="وب سایت" name="Websie" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Website';}" required="">
        <textarea id="txttext" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Your Comment...';}" required="">پیام...</textarea>
        <input type="submit" value="ارسال" onclick="Addcomment()">
    </form>
</div>
<script>
    function Addcomment() {
        $.ajax({
            url: "/News/Comment/" +@Model.id,
            type: "Get",
            data: {
                Name: $("#txtname").val(), Email: $("#txtemail").val(), WebSite: $("#txtweb").val(), Text: $("#txttext").val()
            }

        }).done(function (result) {
            //$("#commentlist").html(result);
            $("#txtname").val("");
            $("#txtemail").val("");
            $("#txtweb").val("");
            $("#txttext").val("");
        });
    }
</script>

IranTimes/Views/Shared/_DefaultLayout.cshtml
@using IranTimes.Models;
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;
@inject UserManager<ApplicationUser> _userManager;
@inject SignInManager<ApplicationUser> _signInManager;

<!DOCTYPE HTML>
<html>
<head>
    <title>خبرگزاری ایران تایمز</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Style Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="applijewelleryion/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="~/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <!-- Custom Theme files -->
    <link href='//fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href="~/css/style.css" rel='stylesheet' type='text/css' />
    <script src="~/js/jquery-1.11.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <!-- animation-effect -->
    <link href="~/css/animate.min.css" rel="stylesheet">
    <script src="~/js/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
    <!-- //animation-effect -->
</head>
<body>
    <div class="header" id="ban">
        <div class="container">

            <div class="header_left wow fadeInRight animated animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInRight;">
                <nav class="navbar navbar-default">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                        <nav class="link-effect-7" id="link-effect-7">
                            <ul class="nav navbar-nav">
                                <li class="active act"><a asp-controller="Home" asp-action="Index">صفحه اصلی</a></li>
                                <li><a asp-controller="Home" asp-action="AboutUs">درباره ما</a></li>
                                <li><a asp-controller="Home" asp-action="ContactUs">تماس با ما</a></li>
                            </ul>
                        </nav>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
            </div>
            @{ 
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = await _userManager.FindByIdAsync(userId);
            }
            @if (user != null)
            {
          
            {
                <div style="display:flex;margin-right:20px;margin-top:10px;justify-content:left"> <p>  @User.Identity.Name  عزیز خوش آمدید / @if ((user.IsPayed == true)) {<a asp-area = "Admin" asp-controller = "Home" asp-action = "Index" > پنل ادمین </a>} / <a asp-controller="Account" asp-action="LogOut">خروج</a></p></div>

                }
            }
            else
            {

                <div style="display:flex;margin-right:30px;margin-top:10px;justify-content:left"><a asp-controller="Account" asp-action="Login">ورود</a>/<a asp-controller="Account" asp-action="Register">ثبت نام</a></div>

            }
            <div class="clearfix"> </div>
        </div>

    </div>
    <div class="header-bottom">
        <div class="container">
            <div class="logo wow fadeInDown animated" data-wow-duration=".8s" data-wow-delay=".2s" style="visibility: visible; animation-duration: 0.8s; animation-delay: 0.2s; animation-name: fadeInDown;">
                <h1><a asp-action="Index">Iran Times</a></h1>
                <p>
                    <label class="of"></label>
                    ایران تایمز یک خبرگزاری متفاوت<label class="on"></label>
                </p>
            </div>
        </div>
    </div>
    <div class="banner">
        <div class="container">
            <h2>ایران تایمز یک خبرگزاری بین المللی است </h2>
            <p>
                شماهم میتوانید در ایران تایمز خبرنگار باشید و گزارش های خود را از سراسر دنیا منتشر کنید فقط کافیست قوانین را
                مطالعه کرده و درصورت نداشتن مشکل ثبت نام کنید
            </p>
            <a asp-controller="Home" asp-action="Ruls">مطالعه قوانین و ثبت نام</a>
        </div>
    </div>
    <div class="technology">
        <div class="container">
            <div class="col-md-9 technology-right">
                <div class="tech-no">
                    @RenderBody()
                </div>
            </div>
            <!-- technology-left -->
            <div class="col-md-3 technology-left">
                <div class="blo-top1">

                    <div class="tech-btm">
                        <div class="search-1 wow fadeInDown animated" data-wow-duration=".8s" data-wow-delay=".2s" style="visibility: visible; animation-duration: 0.8s; animation-delay: 0.2s; animation-name: fadeInDown;">
                            <form asp-controller="Search" asp-action="Index" method="post">
                                <input type="search" name="q" value="جستجو..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}" required="">
                                <input type="submit" value=" ">
                            </form>
                        </div>
                        <h4>
                            پست های محبوب
                        </h4>

                        @await Component.InvokeAsync("Popular")

                        <div class="insta wow fadeInDown animated" data-wow-duration=".8s" data-wow-delay=".2s" style="visibility: visible; animation-duration: 0.8s; animation-delay: 0.2s; animation-name: fadeInDown;">
                            <h4>اینستاگرام</h4>
                            <ul>

                                <li><a href="singlepage.html"><img src="~/images/t1.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="singlepage.html"><img src="~/images/m1.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="singlepage.html"><img src="~/images/f1.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="singlepage.html"><img src="~/images/m2.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="singlepage.html"><img src="~/images/f2.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="singlepage.html"><img src="~/images/t2.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="singlepage.html"><img src="~/images/f3.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="singlepage.html"><img src="~/images/t3.jpg" class="img-responsive" alt=""></a></li>
                                <li><a href="singlepage.html"><img src="~/images/m3.jpg" class="img-responsive" alt=""></a></li>
                            </ul>
                        </div>

                        <p>ما را در اینستاگرام و توییتر دنبال کنید تا از جدید ترین اخبار مطلع شوید </p>
                        <div class="mediaicon">
                            <a href="http://twitter.com" class="fa fa-twitter" style="width:20px;"></a>
                            <a href="http://instagram.com" class="fa fa-instagram" style="width: 20px; margin: auto"></a>
                            <div class="twt">
                            </div>
                          
                            <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'twitter-wjs');</script>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <!-- technology-left -->
        </div>
    </div>

    <div class="footer">
        <div class="container">
            <div class="col-md-4 footer-right wow fadeInDown" data-wow-duration=".8s" data-wow-delay=".2s">
                <h4>درباره من</h4>
                <p>خبرگزاری ایران تایمز که در حال حاضر سرپرستی و مدیریت روزنامه ایران تایمز را بر عهده دارد یک خبرگزاری بین المللی است که هواره مقیاس آن در حال گسترش است از این رو ...</p>
                <img src="images/t4.jpg" class="img-responsive" alt="">
                <div class="bht1">
                    <a asp-action="AboutUs">ادامه مطلب</a>
                </div>
            </div>
            <div class="col-md-4 footer-middle wow fadeInDown" data-wow-duration=".8s" data-wow-delay=".2s">
                <h4>
                    آخرین توییت
                </h4>
                <div class="mid-btm">
                    <p> تیم ملی فوتبال ایران با نتیجه 1 بر 0 در مقابل امارات پیروز میدان شد .</p>
                </div>

                <p> هفته گذشته وزیر امورخارجه کشورمان با سید حسن نصر الله دیدار کرد .</p>

            </div>
            <div class="col-md-4 footer-left wow fadeInDown" data-wow-duration=".8s" data-wow-delay=".2s">
                <h4>
                    عضویت در خبرنامه
                </h4>
                <p>با عضویت در خبرنامه میتوانید از جدیدترین اخبار روز دنیا مطلع شوید </p>
                <div class="name">
                    <form asp-controller="Home" asp-action="NewsLetter" method="post">
                        <input type="text" placeholder="نام و نام خانوادگی" required="">
                        <input type="email" placeholder="ایمیل" required="" style="width:100%;padding:.5em" >                      
                        <input type="submit" value="همین الان عضو خبرنامه شوید" >
                    </form>

                </div>

                <div class="clearfix"> </div>

            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <script src="~/js/modal.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    @RenderSection("Scripts", required: false)


</body>
</html>

IranTimes/Views/Shared/_DropDown.cshtml
@inject IPageGroupRepository _pagegrouprepository
@model Page 
@{ var result = _pagegrouprepository.GetAllGroups();}
    <select asp-for="PageGroupId">
        @foreach (var item in result)
        {
            <option value="@item.Id">@item.GroupName</option>

        }
    </select>

IranTimes/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - IranTimes</title>
        <script src="/js/jquery-1.11.1.min.js"></script>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="/js/bootstrap.min.js"></script>
        <link href="~/css/bootstrap-rtl.css" rel="stylesheet" />
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    </head>
    <body class="rtl">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>                      
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                            </li>
                            @{ if (User.IsInRole("Owner"))
                                {
                                    <li><a class="btn btn-light" asp-area="" asp-controller="UserManager" asp-action="Index">مدیریت کاربران</a></li>
                                    <li><a class="btn btn-light" asp-area="" asp-controller="RoleManager" asp-action="Index">مدیریت مقام ها</a></li>
                                } }
                         

                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>

IranTimes/Views/Shared/_Showcomment.cshtml
<div class="media response-info">
    <div class="media-right response-text-right">
        <a href="#">
            <img src="images/sin1.jpg" class="img-responsive" alt="">
        </a>
    </div>
    <div class="media-body response-text-left">
        <h5>@Model.Name</h5>
        <p>@Model.Text</p>
        <ul>
            <li>@Model.CreateDate</li>
            <li>
                <a href="#">
                    پاسخ
                </a>
            </li>
        </ul>
        <div class="media response-info">
            <div class="media-right response-text-right">
                <a href="#">
                    <img src="images/sin2.jpg" class="img-responsive" alt="">
                </a>
            </div>
            <div class="media-body response-text-left">
                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد</p>
                <ul>
                    <li>July 17, 2016</li>
                    <li>
                        <a href="#">
                            پاسخ
                        </a>
                    </li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div class="clearfix"> </div>
</div> 